### PR TITLE
Add 5.x and 6.1 varnish versions

### PR DESCRIPTION
**Pull request by deees**
## Description

Added support for 5.x and 6.1 varnish versions. Also fixed install of version 5.x with chef 13+:
```
Property major_version must be one of: Float!  You passed 5.
```
A warning in chef 12:
```
Default value 5 is invalid for property major_version of resource varnish_varnish_repo_debian.
In Chef 13 this will become an error: Property major_version must be one of: Float!  You passed 5..
```

### Check List
- [x] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by deees** [comment]
ping @damacus @RyanJarv

**Comment by damacus** [comment]
LGTM, from what I can tell.

I think we want to drop Chef-12 in the next release. @RyanJarv you able to cast your eyes over this please?

**Comment by RyanJarv** [comment]
Hey all, lgtm

**Comment by deees** [comment]
Let's merge and release to supermarket then? 😄

**Comment by gsreynolds** [comment]
Rebased again against master because of #170

**Comment by deees** [comment]
CI did not run after rebase, is it ok?
Is there anything else that I can do to help with the PR?

**Comment by damacus** [comment]
Can someone from @sous-chefs/varnish do a release on this please?

**Pull request merged**
