### PR TITLE
[WIP] Fixes for varnishlog

### PR DESCRIPTION
**Pull request by RyanJarv**
### Description

- Links /etc/sysconfig/varnishlog varnishncsa to defaults file in /etc/default. Fixes https://github.com/sous-chefs/varnish/issues/125.
- Rename default ncsa log file to varnishncsa. This is what is used upstream and also fixes an issue where the ncsa and varnish log output to the same file when you enable ncsa without disabling varnishlog.
- Remove double quotes from default ncsa_format_string, this was likely meant to prevent word splitting in the init.d script but does not work and instead add's quotes to the log format.

### Issues Resolved

* https://github.com/sous-chefs/varnish/issues/125.

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by RyanJarv** [comment]
This includes https://github.com/sous-chefs/varnish/pull/128 as well

**Comment by RyanJarv** [comment]
Other changes:
- Fixes an conflict when using both varnishlog and varnishncsa.
- Fixes distro_install integration tests. https://github.com/sous-chefs/varnish/issues/126
- Reverts the removal of reload-vcl since this is not fixed upstream in ubuntu's system packages yet.
- Adds Ubuntu16.04 tests to .kitchen.doken.yml
- Removes tests varnish repo tests where we can't guarantee the right version will get installed (because the distro one is newer). Added this to README.md under tested versions as well.

**Comment by RyanJarv** [comment]
The failing varnish4-centos-7 check looks like a transient issue. Also noticed that travis isn't running the integration tests for some reason (running ok in kitchen.yml), probably have enough here already so will fix that in another PR.

cc: @rshade

**Comment by rshade** [comment]
Hey man, can you pin the chef version to stable in the .kitchen.dokken for me. I just copied it when I added it and left it on current.

**Comment by RyanJarv** [comment]
Went ahead and merged that, the failure looks like another network issue.

**Pull request merged**
