### PR TITLE
Update resources

### PR DESCRIPTION
**Pull request by damacus**
# Description

- Remove recipes
- Simplify the resources
- Remove old platform support
- Remove support for older version of varnish pre-6.1

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
@damacus can you rebase this please?

Thanks

**Comment by ramereth** [comment]
@damacus looks like you need to resolve the conflicts first

**Comment by kitchen-porter** [comment]
Yeah i mostly just hit save on this one. And realised what a mess it was. I should probably put it back to draft!

**Pull request closed without merging**
